name: "Sample Options"

on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      Environment:
        required: true
        type: choice
        description: "Environment"
        options:
          - dev
          - qa
          - prod
      Region:
        required: true
        type: choice
        description: "Region"
        options:
          - us-central1
          - us-east1
      Project:
        required: true
        type: choice
        description: "Project"
        options:
          - dazzling-matrix-361211
          - dazzling-matrix-361234
      Runtime:
        required: true
        type: choice
        description: "Runtime"
        options:
          - python39
          - python38
          - nodejs16
      EntryPoint:
        required: true
        type: choice
        description: "Entry_point"
        options:
          - hello_gcs
          - my_first_function
          - deploy_code
      EventTriggerType:
        required: true
        type: choice
        description: "Event_trigger_type"
        options:
          - google.storage.object.delete
          - google.storage.object.metadataUpdate
          - google.cloud.pubsub.topic.v1.messagePublished
      EventTriggerResource:
        required: fasle
        type: choice
        description: "Event_trigger_resource"
        options:
          - terraform-state-file-7482
      Memory:
        required: true
        type: choice
        description: "Functions_memory"
        options:
          - 128
          - 256
          - 512

jobs:
  terraform:
    name: "Cloud Functions Update"
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: functions memory update
        uses: google-github-actions/deploy-cloud-functions@v0
        with:
          name: ${{ github.event.inputs.Functions }}
          runtime: ${{ github.event.inputs.Runtime }}
          memory_mb: ${{ github.event.inputs.Memory }}
          source_dir: functions_code/${{ github.event.inputs.Functions }}/
          entry_point: ${{ github.event.inputs.EntryPoint }}
          project_id: ${{ github.event.inputs.Project }}
          event_trigger_type: ${{ github.event.inputs.EventTriggerResource }} 
          event_trigger_resource: projects/${{ github.event.inputs.Project }}/buckets/${{ github.event.inputs.EventTriggerResource }}
          env_vars_file: envars/${{ github.event.inputs.Functions }}.yaml
