name: "Sample Options"

on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      Environment:
        required: true
        type: choice
        description: "Environment"
        options:
          - dev
          - qa
          - prod
      Region:
        required: true
        type: choice
        description: "Region"
        options:
          - us-east1
          - us-central1
      Project:
        required: true
        type: choice
        description: "Project"
        options:
          - dazzling-matrix-361211
          - dazzling-matrix-361234
      Functions:
        required: true
        type: choice
        description: "Function Name"
        options:
          - test-function
          - demo-function
      Parameter:
        required: true
        type: choice
        description: "Functions Parameter"
        options:
          - Code
          - Memory
          - Environment_variables
      Code:
        required: true
        type: choice
        description: "Functions code"
        options:
          - functions_code/test-functions
          - functions_code/demo-functions
      Memory:
        required: true
        type: choice
        description: "Functions Memory"
        options:
          - 128
          - 256
          - 512
      Environment_variables:
        required: true
        type: choice
        description: "Functions Environmental Variables"
        options:
          - functions_code/test_functions/env
          - functions_code/demo_functions/env

env:
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

jobs:
  terraform:
    name: "Cloud Functions Update"
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: functions code update
        uses: actions-hub/gcloud@master
        if: ${{ github.event.inputs.Parameter == 'Code' }}
        run: |
          echo "Updating functions Code"
          echo "Project environment: ${{ github.event.inputs.Environment }}"
          echo "Function Name: ${{ github.event.inputs.Functions }}"

      - name: functions memory update
        uses: actions-hub/gcloud@master
        if: ${{ github.event.inputs.Parameter == 'Memory' }}
        run: |
          echo "Updating functions Memory"
          echo "Project environment: ${{ github.event.inputs.Environment }}"
          echo "Function Name: ${{ github.event.inputs.Functions }}"
          gcloud functions deploy ${{ github.event.inputs.Functions }} --region ${{ github.event.inputs.Region }} --project ${{ github.event.inputs.Project }}  --memory ${{ github.event.inputs.Memory }}MB"

      - name: functions env update
        uses: actions-hub/gcloud@master
        if: ${{ github.event.inputs.Parameter == 'Environment_variables' }}
        run: |
          echo "Updating functions Environment Variables"
          echo "Project environment: ${{ github.event.inputs.Environment }}"
          echo "Function Name: ${{ github.event.inputs.Functions }}"
